-- hOW TO USE SUM AND COMMAND %TYPE

SET SERVEROUTPUT ON

DECLARE
  V_SUM_SAL NUMBER(10,2);
  V_FIRST_NAME HR.EMPLOYEES.FIRST_NAME%TYPE; -- IT TAKES THE TYPE OF VARIABLE FROM THE TABLE, IT AVOIDES FUTURE BUGS.
  V_LAST_NAME HR.EMPLOYEES.LAST_NAME%TYPE;
  
BEGIN

  SELECT SUM(nvl(SALARY,0)) INTO V_SUM_SAL -- COMMAND SUM OF ALL SALARIES FROM A SPECIFIC DEPARTMENT.
  FROM HR.EMPLOYEES
  WHERE DEPARTMENT_ID = 10;
  DBMS_OUTPUT.put_line('The sum of salaries is: ' || V_SUM_SAL); 
  
  SELECT FIRST_NAME, LAST_NAME INTO V_FIRST_NAME, V_LAST_NAME -- SELECT FIRST NAME AND LAST NAME FROM A SPECIFIC EMPLOYEE
  FROM HR.EMPLOYEES
  WHERE EMPLOYEE_ID = 100;
  
  DBMS_OUTPUT.PUT_LINE('The full name of employee is: '|| V_FIRST_NAME || ' ' || V_LAST_NAME );
  

END;
